org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonFinalResIds=false

# Memory & Incremental Build Fixes to Prevent Android Studio Deployment Cache Corruption
android.injected.testOnly=false
ksp.incremental=true
ksp.incremental.intermodule=true
org.gradle.caching=true
org.gradle.parallel=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
