ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.trackly.ApplicationKt.module ]
    }
}

jwt {
    domain = "https://trackly.com"
    audience = "trackly-users"
    realm = "Trackly Backend API"
    secret = "trackly_secret_key_sde2_production_grade_super_secure_jwt_token"
}

database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/trackly"
    user = "postgres"
    password = "postgres_password"
}
